import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions | AI Creator Suite",
  description:
    "Read the terms and conditions for using our AI thumbnail, tag, and keyword tools.",
  keywords: [
    "terms and conditions",
    "website terms of service",
    "ai tool terms",
  ],
};
const page = () => {
  return (
    <>
      <main className="min-h-screen bg-background">
        <div className="container max-w-4xl mx-auto px-6 py-20">
          <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>

          <p className="text-sm text-muted-foreground mb-12">
            Last updated: February 23, 2026
          </p>

          <div className="space-y-10 text-muted-foreground leading-7">
            <section>
              <p>
                By accessing and using our website and AI tools, you agree to
                these Terms of Service. Please read them carefully before using
                our platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                1. Services Provided
              </h2>
              <p>
                We provide AI-powered tools including thumbnail generation,
                hashtag generation, keyword research, and media utilities for
                creators and marketers.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                2. Acceptable Use
              </h2>
              <ul className="list-disc ml-6 space-y-1">
                <li>Do not use the service for illegal activities</li>
                <li>Do not upload copyrighted or harmful content</li>
                <li>Do not abuse, scrape, or overload our servers</li>
                <li>Do not attempt to bypass system limits or security</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                3. AI Generated Content
              </h2>
              <p>
                Results generated by AI may not always be accurate or unique.
                You are responsible for reviewing and verifying any generated
                output before publishing or using it commercially.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                4. Intellectual Property
              </h2>
              <p>
                The website, branding, and software remain our property. You may
                not copy, resell, or redistribute our platform or code without
                permission.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                5. Third-Party Services
              </h2>
              <p>
                Some features may rely on external providers such as{" "}
                <span className="font-medium">OpenAI</span>,{" "}
                <span className="font-medium">Anthropic</span>, or{" "}
                <span className="font-medium">Google</span>.
                 We are not
                responsible for outages or issues caused by third-party
                services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                6. Limitation of Liability
              </h2>
              <p>
                We provide services "as is" without warranties. We are not
                liable for any loss, damages, or data issues resulting from use
                of the platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                7. Termination
              </h2>
              <p>
                We reserve the right to suspend or block access if users violate
                these terms or misuse the platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                8. Changes to Terms
              </h2>
              <p>
                We may update these terms at any time. Continued use of the
                service means you accept the revised terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                9. Contact
              </h2>
              <p>Email: support@boltcreator.online</p>
            </section>
          </div>
        </div>
      </main>
    </>
  );
};

export default page;
