export const offlinePlan = [
  {
    id: "free",
    name: "Free",
    description: "Try the platform risk-free",
    monthly: 0,
    yearly: 0,
    highlight: false,
    features: [
      "30 AI thumbnail generations / month",
      "Unlimited tags & keyword tools",
      "Unlimited tag extractor",
      "Watermarked exports",
      "Standard speed queue",
      "Community support",
    ],
    buttonText: "Start Free",
    url: "/signup",
  },
  {
    id: "pro",
    monthlyPlanId: "plan_SNuqOid3vopvhN",
    yearlyPlanId: "plan_SNvsI7uq64Prqj",
    name: "Pro",
    description: "Perfect for growing creators",
    monthly: 599,
    yearly: 4999,
    highlight: true,
    features: [
      "300 thumbnails / month",
      "Unlimited SEO tools",
      "No watermark",
      "Premium templates",
      "HD downloads",
      "Generation history",
      "Fast priority queue",
      "Email support",
    ],
    buttonText: "Upgrade to Pro",
    url: "/signup",
  },
  {
    id: "creator",
    monthlyPlanId: "plan_SNvuCaLmLtEtZh",
    yearlyPlanId: "plan_SNvwfidE7ZgAMQ",
    name: "Creator",
    description: "Unlimited for professionals & teams",
    monthly: 999,
    yearly: 8999,
    highlight: false,
    features: [
      "Unlimited thumbnails",
      "Unlimited SEO tools",
      "Bulk generation",
      "Team access",
      "Fastest private queue",
      "Commercial license",
      "Early features",
      "Priority support",
    ],
    buttonText: "Go Unlimited",
    url: "/signup",
  },
];
export const onlinePlan = [
  {
    id: "free",
    name: "Free",
    description: "Try the platform risk-free",
    monthly: 0,
    yearly: 0,
    highlight: false,
    features: [
      "30 AI thumbnail generations / month",
      "Unlimited tags & keyword tools",
      "Unlimited tag extractor",
      "Watermarked exports",
      "Standard speed queue",
      "Community support",
    ],
    buttonText: "Start Free",
    url: "/signup",
  },
  {
    id: "pro",
    monthlyPlanId: "plan_SNuqOid3vopvhN",
    yearlyPlanId: "plan_SNvsI7uq64Prqj",
    name: "Pro",
    description: "Perfect for growing creators",
    monthly: 599,
    yearly: 4999,
    highlight: true,
    features: [
      "300 thumbnails / month",
      "Unlimited SEO tools",
      "No watermark",
      "Premium templates",
      "HD downloads",
      "Generation history",
      "Fast priority queue",
      "Email support",
    ],
    buttonText: "Upgrade to Pro",
    url: "/signup",
  },
  {
    id: "creator",
    monthlyPlanId: "plan_SNvuCaLmLtEtZh",
    yearlyPlanId: "plan_SNvwfidE7ZgAMQ",
    name: "Creator",
    description: "Unlimited for professionals & teams",
    monthly: 999,
    yearly: 8999,
    highlight: false,
    features: [
      "Unlimited thumbnails",
      "Unlimited SEO tools",
      "Bulk generation",
      "Team access",
      "Fastest private queue",
      "Commercial license",
      "Early features",
      "Priority support",
    ],
    buttonText: "Go Unlimited",
    url: "/signup",
  },
];

// export const offlinePlan = [
//   {
//     id: "free",
//     name: "Free",
//     description: "Try the platform risk-free",
//     monthly: 0,
//     yearly: 0,
//     highlight: false,
//     features: [
//       "30 AI thumbnail generations / month",
//       "Unlimited tags & keyword tools",
//       "Unlimited tag extractor",
//       "Watermarked exports",
//       "Standard speed queue",
//       "Community support",
//     ],
//     buttonText: "Start Free",
//     url: "/signup",
//   },
//   {
//     id: "pro",
//     monthlyPlanId: "plan_SNuqOid3vopvhN",
//     yearlyPlanId: "plan_SNvsI7uq64Prqj",
//     name: "Pro",
//     description: "Perfect for growing creators",
//     monthly: 7,
//     yearly: 60,
//     highlight: true,
//     features: [
//       "300 thumbnails / month",
//       "Unlimited SEO tools",
//       "No watermark",
//       "Premium templates",
//       "HD downloads",
//       "Generation history",
//       "Fast priority queue",
//       "Email support",
//     ],
//     buttonText: "Upgrade to Pro",
//     url: "/signup",
//   },
//   {
//     id: "creator",
//     monthlyPlanId: "plan_SNvuCaLmLtEtZh",
//     yearlyPlanId: "plan_SNvwfidE7ZgAMQ",
//     name: "Creator",
//     description: "Unlimited for professionals & teams",
//     monthly: 12,
//     yearly: 120,
//     highlight: false,
//     features: [
//       "Unlimited thumbnails",
//       "Unlimited SEO tools",
//       "Bulk generation",
//       "Team access",
//       "Fastest private queue",
//       "Commercial license",
//       "Early features",
//       "Priority support",
//     ],
//     buttonText: "Go Unlimited",
//     url: "/signup",
//   },
// ];
// export const onlinePlan = [
//   {
//     id: "free",
//     name: "Free",
//     description: "Try the platform risk-free",
//     monthly: 0,
//     yearly: 0,
//     highlight: false,
//     features: [
//       "30 AI thumbnail generations / month",
//       "Unlimited tags & keyword tools",
//       "Unlimited tag extractor",
//       "Watermarked exports",
//       "Standard speed queue",
//       "Community support",
//     ],
//     buttonText: "Start Free",
//     url: "/signup",
//   },
//   {
//     id: "pro",
//     monthlyPlanId: "plan_SP4bUHqL0ug9NF",
//     yearlyPlanId: "plan_SP4bUyJvcgRsBE",
//     name: "Pro",
//     description: "Perfect for growing creators",
//     monthly: 7,
//     yearly: 60,
//     highlight: true,
//     features: [
//       "300 thumbnails / month",
//       "Unlimited SEO tools",
//       "No watermark",
//       "Premium templates",
//       "HD downloads",
//       "Generation history",
//       "Fast priority queue",
//       "Email support",
//     ],
//     buttonText: "Upgrade to Pro",
//     url: "/signup",
//   },
//   {
//     id: "creator",
//     monthlyPlanId: "plan_SP4bVcWrMnarXV",
//     yearlyPlanId: "plan_SP4bWDFkgr0Jrr",
//     name: "Creator",
//     description: "Unlimited for professionals & teams",
//     monthly: 12,
//     yearly: 120,
//     highlight: false,
//     features: [
//       "Unlimited thumbnails",
//       "Unlimited SEO tools",
//       "Bulk generation",
//       "Team access",
//       "Fastest private queue",
//       "Commercial license",
//       "Early features",
//       "Priority support",
//     ],
//     buttonText: "Go Unlimited",
//     url: "/signup",
//   },
// ];
